#!/bin/sh

WORDNETAPI_HOME="`dirname $0`"

#JAVA_OPTS="$JAVA_OPTS -Djava.util.logging.config.file=$WORDNETAPI_HOME/logging.properties"
WORDNETAPI_CLASSPATH=$WORDNETAPI_HOME/lib/wordnetapi.jar
WORDNETAPI_CLASSPATH=$WORDNETAPI_CLASSPATH:$WORDNETAPI_HOME/ext/h2.jar
WORDNETAPI_CLASSPATH=$WORDNETAPI_CLASSPATH:$WORDNETAPI_HOME/ext/toplink-essentials.jar
WORDNETAPI_CLASSPATH=$WORDNETAPI_CLASSPATH:$WORDNETAPI_HOME/database

MAIN=eu.kostia.main.WordnetCLI

java $JAVA_OPTS -classpath "$WORDNETAPI_CLASSPATH" $MAIN $*